# Generated by Django 5.1.1 on 2024-10-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('mood', models.CharField(choices=[('T', 'Turn Up'), ('C', 'Calm Vibes'), ('R', 'Romantic Vibes'), ('P', 'Productive Tunes'), ('S', 'Sad Vibes')], default='Calm Vibes', max_length=20)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vinyl')),
            ],
        ),
    ]
