# Generated by Django 5.1.1 on 2024-10-02 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Latest Listening1 date'),
            preserve_default=False,
        ),
    ]
