# Generated by Django 5.1.1 on 2024-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_song_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(verbose_name='Latest Listening date'),
        ),
    ]
