# Generated by Django 5.1.1 on 2024-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
