# Generated by Django 5.1.1 on 2024-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_playlist_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
